apiVersion: v1
kind: Pod
metadata:
  name: mysqldb
  labels:
    app: mysqldb
spec:
  containers:
    - name: container-mysql
      image: mysql
      ports:
        - containerPort: 3306
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"  
      envFrom:
        - configMapRef:
            name: configmap-db