apiVersion: v1
kind: Pod
metadata:
  name: nginxapp
  labels:
    app: nginxapp
spec:
  containers:
    - name: container-nginx
      image: nginx:stable
      ports:
        - containerPort: 80
      resources:
        limits:
          memory: "128Mi"
          cpu: "1"  